# Generated by Django 4.2 on 2026-05-12 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=80)),
                ("specialty", models.CharField(blank=True, max_length=200)),
                ("bio_published_html", models.TextField(blank=True)),
                ("bio_draft_html", models.TextField(blank=True)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="doctors/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "draft_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("draft_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("draft_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("draft_review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "user__name", "user__username"),
            },
        ),
    ]
