# Generated by Django 4.2 on 2026-05-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_doctorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_links",
                        to="content.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_links",
                        to="content.doctorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="doctordepartment",
            constraint=models.UniqueConstraint(
                fields=("doctor", "department"), name="uniq_doctor_department_pair"
            ),
        ),
    ]
