#!/usr/bin/env bash
# service-common/envgen.sh — generate a production .env with strong random
# secrets for a target server. SOURCE this file; do not execute directly.
#
# Env contract verified against backend/config/settings.py:
#   REQUIRED_PROD_ENV = DJANGO_SECRET_KEY, DJANGO_ALLOWED_HOSTS,
#   POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST.
#   DJANGO_SECRET_KEY must differ from the dev default.

# URL-safe-ish random string of N bytes of entropy.
gen_secret() {
  local bytes="${1:-32}"
  if _have openssl; then
    openssl rand -base64 "$bytes" | tr -d '\n=+/' | cut -c1-"$((bytes))"
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$bytes"
  fi
}

# generate_env <host_ip> <env_outfile> <cred_outfile>
# Writes a complete production .env to <env_outfile> and a human-readable
# credentials summary to <cred_outfile>. Returns the admin password via the
# global GENERATED_ADMIN_PASSWORD for callers that want to print it.
generate_env() {
  local ip="$1" env_out="$2" cred_out="$3"

  local secret_key pg_pw admin_pw minio_pw
  secret_key="$(gen_secret 50)"
  pg_pw="$(gen_secret 24)"
  admin_pw="$(gen_secret 20)"
  minio_pw="$(gen_secret 24)"
  GENERATED_ADMIN_PASSWORD="$admin_pw"

  cat >"$env_out" <<EOF
# Generated by service-deploy for ${ip} — production stack
ENV=production

# Django
DJANGO_SECRET_KEY=${secret_key}
DJANGO_DEBUG=0
DJANGO_ALLOWED_HOSTS=${ip},localhost,127.0.0.1
DJANGO_CORS_ALLOWED_ORIGINS=http://${ip}:5173,http://localhost:5173

# PostgreSQL
POSTGRES_DB=clinic
POSTGRES_USER=clinic
POSTGRES_PASSWORD=${pg_pw}
POSTGRES_HOST=db
POSTGRES_PORT=5432

# Auto-created Django superuser
DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_EMAIL=admin@example.com
DJANGO_SUPERUSER_PASSWORD=${admin_pw}

# Gunicorn (2c4g recommended)
GUNICORN_WORKERS=2
GUNICORN_TIMEOUT=120
GUNICORN_MAX_REQUESTS=1000
GUNICORN_MAX_REQUESTS_JITTER=100

# Build mirrors (default: mainland China)
APT_MIRROR=mirrors.tuna.tsinghua.edu.cn
PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn

HOST_IP=${ip}

# MinIO (S3-compatible object storage for portal media)
MINIO_ROOT_USER=clinic
MINIO_ROOT_PASSWORD=${minio_pw}
MINIO_BUCKET=clinic-media
MINIO_ENDPOINT=http://minio:9000
MINIO_PUBLIC_ENDPOINT=http://${ip}:9000
EOF

  umask 077
  cat >"$cred_out" <<EOF
# Credentials for ${ip} — generated $(date '+%Y-%m-%d %H:%M:%S')
# KEEP PRIVATE. This file is gitignored and never pushed to the server.
FRONTEND_URL=http://${ip}:5173
BACKEND_API=http://${ip}:8000/api/
SWAGGER=http://${ip}:8000/api/docs/swagger/
MINIO_CONSOLE=http://${ip}:9001

ADMIN_USERNAME=admin
ADMIN_PASSWORD=${admin_pw}

POSTGRES_PASSWORD=${pg_pw}
MINIO_ROOT_USER=clinic
MINIO_ROOT_PASSWORD=${minio_pw}
DJANGO_SECRET_KEY=${secret_key}
EOF
  chmod 600 "$cred_out" 2>/dev/null || true
}
