# Generated by Django 4.2 on 2026-02-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
