# Generated by Django 4.2 on 2026-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_data_user_avatar_size_user_avatar_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="Medical Booking Platform", max_length=120
                    ),
                ),
                ("logo_data", models.TextField(blank=True)),
                ("logo_type", models.CharField(blank=True, max_length=50)),
                ("logo_size", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
