# Generated by Django 4.2 on 2026-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("operator", "Operations"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
